version: '3.8'
services:
  info_bot:
    container_name: info_bot
    build: .
    image: info_bot_image:latest
    restart: always
    volumes:
      - ./:/code
    ports:
      - "${SVC_PORT}:${SVC_PORT}"
    networks:
      - info-bot-network
    depends_on:
      - info_bot_db

  info_bot_db:
    container_name: info_bot_db
    image: mongo:6-jammy
    restart: always
    command: mongod --port ${MONGODB_PORT}
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    environment:
      TZ: "Asia/Tashkent"
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - info_bot_data:/data/db
    networks:
      - info-bot-network
volumes:
  info_bot_data:
    name: info_bot_data

networks:
  info-bot-network:
    name: info-bot-network